### PR TITLE
remove unused parameter 'clients'

### PR DESCRIPTION
**Pull request by prashantjois**

### CODE REVIEW

**Comment by uohzxela** [comment]
Thanks for the catch! I think it'd be better if we can propagate `clients` as an argument instead of treating it as an ambiguous global variable. What do you think?

```
def email_active_clients(clients)
  active_clients(clients).each { |client| email(client) }
end

def active_clients(clients)
  clients.select { |client| active_client?(client) }
end
```

**Comment by prashantjois** [comment]
I think it would be better if the function was just `email_clients` and you can pass it in the clients you want.  This will keep with the principle that the method should take exactly what it needs.  I was thinking something like this:

```
def email_clients(clients)
  clients.each { |client| email(client) }
end

def active_clients(clients)
  clients.select { |client| active_client?(client) }
end

email_clients(active_clients(clients))
```

What are your thoughts on that?

**Comment by uohzxela** [comment]
I like this change better! This makes the `email_clients` method more reusable. Please add the `clients` parameter to the `active_clients` method and we are good to go!

**Comment by prashantjois** [comment]
Fixed, please have a look!

**Comment by uohzxela** [comment]
Looks great! But I believe the `active_clients` method is still missing the `clients` parameter?

**Comment by prashantjois** [comment]
Oops thank you

**Comment by uohzxela** [comment]
Awesome, thank you so much! ❤️

**Pull request merged**
